services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./conf.d:/etc/nginx/conf.d:ro
    restart: unless-stopped
    networks:
      - mitmproxy_net
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  mitmproxy_net:
    external: true
