---
- name: Deploy PostgreSQL
  hosts: postgres
  become: true
  vars_files:
    - ../../vars/postgres/main.yml
    - ../../group_vars/all/all.yml

  roles:
    - role: docker
      vars:
        # rollback: true
        debug: true
        container_volumes:
          - postgres_data
        container_name: "postgres"
        # (important) prevent wiping data when redeploying
        remove_volumes: false
